// Emacs style mode select   -*- C++ -*- 
//-----------------------------------------------------------------------------
//
// $Id:$
//
// Copyright (C) 1993-1996 by id Software, Inc.
//
// This source is available for distribution and/or modification
// only under the terms of the DOOM Source Code License as
// published by id Software. All rights reserved.
//
// The source is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// FITNESS FOR A PARTICULAR PURPOSE. See the DOOM Source Code License
// for more details.
//
// $Log:$
//
// DESCRIPTION:
//	DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//	plus functions to determine game mode (shareware, registered),
//	parse command line parameters, configure game parameters (turbo),
//	and call the startup functions.
//
//-----------------------------------------------------------------------------


static const char rcsid[] = "$Id: d_main.c,v 1.8 1997/02/03 22:45:09 b1 Exp $";

#define	BGCOLOR		7
#define	FGCOLOR		8


#include <stdio.h>
#include <stdlib.h>

extern int access(char *file, int mode);

#define R_OK	4
#if 0
static int access(char *file, int mode)
{
	FILE *test_fp;

	test_fp = fopen(file, "r");
	if ( test_fp != NULL ) {
		fclose(test_fp);
		return(0);
	}
	return(-1);
}
#endif


#include "doomdef.h"
#include "doomstat.h"

#include "dstrings.h"
#include "sounds.h"


#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"

#include "f_finale.h"
#include "f_wipe.h"

#include "m_argv.h"
#include "m_misc.h"
#include "m_menu.h"

#include "i_system.h"
#include "i_sound.h"
#include "i_video.h"

#include "g_game.h"
#include "heretic.h"		// Heretic_Init -- additive Heretic monsters
#include "hexen.h"		// Hexen_Init   -- additive Hexen monsters
#include "freedoom.h"		// Freedoom_Init -- cloned DOOM2 monsters (free art)
#include "revmarine.h"		// RevMarine_Init -- (G) revived friendly marine actor
#include "p_invent.h"		// Invent_Init -- (J) artifact inventory pickups
#include "g_agent.h"		// G_AgentInit -- full agent/LLM player control (-aiplayer)

#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"

#include "p_setup.h"
#include "p_ai_coop.h"
#include "p_ai_director.h"
#include "c_console.h"
#include "i_udp.h"		// Chocolate/Crispy net: UDP + packet layer (-querychoc/-chocsyn)
#include "d_netcl.h"		// Chocolate/Crispy net client (-connect/-netclient)
#include "r_local.h"


#include "d_main.h"

//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);


char*		wadfiles[MAXWADFILES];

// Set when playing DOOM1 with doom2stuff.wad auto-overlaid: enables the DOOM2
// monsters (director) and the super shotgun even though doom.wad lacks the assets.
int		doom2_overlay = 0;


boolean		devparm;	// started game with -devparm
boolean         nomonsters;	// checkparm of -nomonsters
boolean         respawnparm;	// checkparm of -respawn
boolean         fastparm;	// checkparm of -fast

boolean         drone;

boolean		singletics = false; // debug flag to cancel adaptiveness



//extern int soundVolume;
//extern  int	sfxVolume;
//extern  int	musicVolume;

extern  boolean	inhelpscreens;

skill_t		startskill;
int             startepisode;
int		startmap;
boolean		autostart;

FILE*		debugfile;

boolean		advancedemo;




char		wadfile[1024];		// primary wad file
char		mapdir[1024];           // directory of development maps
char		basedefault[1024];      // default file


void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t         events[MAXEVENTS];
int             eventhead;
int 		eventtail;


//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t* ev)
{
    events[eventhead] = *ev;
    eventhead = (++eventhead)&(MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t*	ev;
	
    // IF STORE DEMO, DO NOT ACCEPT INPUT
    if ( ( gamemode == commercial )
	 && (W_CheckNumForName("map01")<0) )
      return;
	
    for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) )
    {
	ev = &events[eventtail];
	if (C_Responder (ev))
	    continue;               // console ate the event
	if (M_Responder (ev))
	    continue;               // menu ate the event
	G_Responder (ev);
    }
}




//
// D_Display
//  draw current display, possibly wiping it from the previous
//

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t     wipegamestate = GS_DEMOSCREEN;
extern  boolean setsizeneeded;
extern  int             showMessages;
void R_ExecuteSetViewSize (void);

void D_Display (void)
{
    static  boolean		viewactivestate = false;
    static  boolean		menuactivestate = false;
    static  boolean		inhelpscreensstate = false;
    static  boolean		fullscreen = false;
    static  gamestate_t		oldgamestate = -1;
    static  int			borderdrawcount;
    int				nowtime;
    int				tics;
    int				wipestart;
    int				y;
    boolean			done;
    boolean			wipe;
    boolean			redrawsbar;

    if (nodrawers)
	return;                    // for comparative timing / profiling
		
    redrawsbar = false;
    
    // change the view size if needed
    if (setsizeneeded)
    {
	R_ExecuteSetViewSize ();
	oldgamestate = -1;                      // force background redraw
	borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
	wipe = true;
	wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
	wipe = false;

    if (gamestate == GS_LEVEL && gametic)
	HU_Erase();
    
    // do buffered drawing
    switch (gamestate)
    {
      case GS_LEVEL:
	if (!gametic)
	    break;
	if (automapactive)
	    AM_Drawer ();
	if (wipe || (viewheight != SCREENHEIGHT && fullscreen) )
	    redrawsbar = true;
	if (inhelpscreensstate && !inhelpscreens)
	    redrawsbar = true;              // just put away the help screen
	if (menuactivestate)
	    redrawsbar = true;             // the menu can overdraw the status bar
					  //  (e.g. the 2x "Video" item) -- repaint it
	// status bar is drawn *after* R_RenderPlayerView below -- in widescreen the
	// view is full-height and would otherwise overwrite the centred bar.
	break;

      case GS_INTERMISSION:
	WI_Drawer ();
	break;

      case GS_FINALE:
	F_Drawer ();
	break;

      case GS_DEMOSCREEN:
	D_PageDrawer ();
	break;
    }
    
    // draw buffered stuff to screen
    I_UpdateNoBlit ();
    
    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic)
    {
	// Safety: if the spied-on player (F12 spy mode) lost its body since we
	// switched to it -- a co-op/AI buddy mid-death/reborn -- snap back to our
	// own view rather than deref a NULL mo in R_SetupFrame.
	if (!playeringame[displayplayer] || !players[displayplayer].mo)
	    displayplayer = consoleplayer;
	R_RenderPlayerView (&players[displayplayer]);
	R_DrawCrosshair ();		// over the 3D view, under the HUD/menu/console
    }

    // Status bar, drawn AFTER the view: in widescreen the bar mode renders a
    // full-height view (game beside the bar), so the bar must overlay it.  Minimal
    // HUD (no bar) only when the view is full AND the user didn't ask for the bar
    // (setblocks==11), so widescreen's full-height bar mode still shows the bar.
    if (gamestate == GS_LEVEL && gametic)
    {
	extern int setblocks;
	boolean st_minimal = (viewheight == SCREENHEIGHT)
			     && !(widescreen && setblocks <= 10);
	// widescreen bar overlays a full-height view that overwrites it every frame,
	// so force a full bar redraw (background + widgets) each tic.
	boolean ws_bar = widescreen && setblocks <= 10 && !st_minimal;
	ST_Drawer (st_minimal, redrawsbar || ws_bar);
	fullscreen = st_minimal;
    }

    if (gamestate == GS_LEVEL && gametic)
	HU_Drawer ();
    
    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
	I_SetPalette (W_CacheLumpName ("PLAYPAL",PU_CACHE));

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
	viewactivestate = false;        // view was not active
	R_FillBackScreen ();    // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != SCREENWIDTH)
    {
	if (menuactive || menuactivestate || !viewactivestate)
	    borderdrawcount = 3;
	if (borderdrawcount)
	{
	    R_DrawViewBorder ();    // erase old menu stuff
	    borderdrawcount--;
	}

    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;
    
    // draw pause pic
    if (paused)
    {
	if (automapactive)
	    y = 4;
	else
	    y = viewwindowy+4;
	V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2,
			  y,0,W_CacheLumpName ("M_PAUSE", PU_CACHE));
    }


    // menus go directly to the screen
    M_Drawer ();          // menu is drawn even on top of everything
    C_Drawer ();          // console overlays everything
    NetUpdate ();         // send out any new accumulation


    // normal update
    if (!wipe)
    {
	I_FinishUpdate ();              // page flip or blit buffer
	return;
    }
    
    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);

    wipestart = I_GetTime () - 1;

    do
    {
	do
	{
	    nowtime = I_GetTime ();
	    tics = nowtime - wipestart;
	} while (!tics);
	wipestart = nowtime;
	done = wipe_ScreenWipe(wipe_Melt
			       , 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
	I_UpdateNoBlit ();
	M_Drawer ();                            // menu is drawn even on top of wipes
	I_FinishUpdate ();                      // page flip or blit buffer
    } while (!done);
}



//
//  D_DoomLoop
//
extern  boolean         demorecording;

void D_DoomLoop (void)
{
    if (demorecording)
	G_BeginRecording ();
		
    if (M_CheckParm ("-debugfile"))
    {
	char    filename[20];
	sprintf (filename,"debug%i.txt",consoleplayer);
	printf ("debug output to: %s\n",filename);
	debugfile = fopen (filename,"w");
    }
	
    I_InitGraphics ();

    while (1)
    {
	// frame syncronous IO operations
	I_StartFrame ();                
	
	// process one or more tics
	if (singletics)
	{
	    I_StartTic ();
	    D_ProcessEvents ();
	    G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);
	    if (advancedemo)
		D_DoAdvanceDemo ();
	    M_Ticker ();
	    G_Ticker ();
	    gametic++;
	    maketic++;
	}
	else
	{
	    TryRunTics (); // will run at least one tic
	}

	S_UpdateSounds (players[consoleplayer].mo);// move positional sounds

	// Update display, next frame, with current state.
	D_Display ();
    }
}



//
//  DEMO LOOP
//
int             demosequence;
int             pagetic;
char                    *pagename;


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
	D_AdvanceDemo ();
}



//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    V_DrawPatch (0,0, 0, W_CacheLumpName(pagename, PU_CACHE));
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
 void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE;  // not reborn
    advancedemo = false;
    usergame = false;               // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if ( gamemode == retail )
      demosequence = (demosequence+1)%7;
    else
      demosequence = (demosequence+1)%6;
    
    switch (demosequence)
    {
      case 0:
	if ( gamemode == commercial )
	    pagetic = 35 * 11;
	else
	    pagetic = 170;
	gamestate = GS_DEMOSCREEN;
	pagename = "TITLEPIC";
	if ( gamemode == commercial )
	  S_StartMusic(mus_dm2ttl);
	else
	  S_StartMusic (mus_intro);
	break;
      case 1:
	G_DeferedPlayDemo ("demo1");
	break;
      case 2:
	pagetic = 200;
	gamestate = GS_DEMOSCREEN;
	pagename = "CREDIT";
	break;
      case 3:
	G_DeferedPlayDemo ("demo2");
	break;
      case 4:
	gamestate = GS_DEMOSCREEN;
	if ( gamemode == commercial)
	{
	    pagetic = 35 * 11;
	    pagename = "TITLEPIC";
	    S_StartMusic(mus_dm2ttl);
	}
	else
	{
	    pagetic = 200;

	    if ( gamemode == retail )
	      pagename = "CREDIT";
	    else
	      pagename = "HELP2";
	}
	break;
      case 5:
	G_DeferedPlayDemo ("demo3");
	break;
        // THE DEFINITIVE DOOM Special Edition demo
      case 6:
	G_DeferedPlayDemo ("demo4");
	break;
    }
}



//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}




//      print title for every printed line
char            title[128];



//
// D_AddFile
//
void D_AddFile (char *file)
{
    int     numwadfiles;
    char    *newfile;
	
    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
	;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);
	
    wadfiles[numwadfiles] = newfile;
}

//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
// Known IWAD filenames in detection priority, with the game mode they imply.
static const struct { const char* name; int mode; } known_iwads[] = {
    { "doom2.wad",     commercial },
    { "plutonia.wad",  commercial },
    { "tnt.wad",       commercial },
    { "doomu.wad",     retail     },
    { "doom.wad",      registered },
    { "doom1.wad",     shareware  },
    { "freedoom2.wad", commercial },
    { "freedoom1.wad", retail     },
    { "freedm.wad",    commercial },
    { "chex3.wad",     retail     },	// Chex Quest 3 (Ultimate-Doom format)
};

// Steam install locations (relative to steamapps/common) + game mode.
static const struct { const char* rel; int mode; } steam_iwads[] = {
    { "Ultimate Doom/base/DOOM.WAD",       retail     },
    { "Ultimate Doom/rerelease/DOOM.WAD",  retail     },
    { "Ultimate Doom/base/doom.wad",       retail     },
    { "DOOM 2/base/DOOM2.WAD",             commercial },
    { "Doom 2/base/DOOM2.WAD",             commercial },
    { "Doom 2/finaldoombase/TNT.WAD",      commercial },
    { "Doom 2/finaldoombase/PLUTONIA.WAD", commercial },
    { "Final Doom/base/TNT.WAD",           commercial },
    { "Final Doom/base/PLUTONIA.WAD",      commercial },
};

static char* IWAD_Strdup (const char* s)
{
    char* d = malloc(strlen(s)+1);
    if (d) strcpy(d, s);
    return d;
}

// Read a value for "key" from aidoom.cfg (working dir). Returns 1 if found.
static int IWAD_CfgGet (const char* key, char* out, int n)
{
    FILE* f = fopen("aidoom.cfg", "r");
    char line[256], k[64], v[192];
    int found = 0;
    if (!f) return 0;
    while (fgets(line, sizeof(line), f))
    {
	if (sscanf(line, " %63s %191[^\n]", k, v) == 2 && !strcmp(k, key))
	{
	    char* p = v; int L = (int)strlen(p);
	    if (L >= 2 && p[0]=='"' && p[L-1]=='"') { p[L-1]=0; p++; }
	    strncpy(out, p, n-1); out[n-1]=0; found = 1;
	}
    }
    fclose(f);
    return found;
}

// Best-effort game mode from an IWAD path's basename.
static int IWAD_ModeFromName (const char* path)
{
    const char* b = path; const char* s;
    char low[64]; int i, c;
    if ((s = strrchr(b,'/')))  b = s+1;
    if ((s = strrchr(b,'\\'))) b = s+1;
    for (i=0; b[i] && i<63; i++) { c = b[i]; if (c>='A'&&c<='Z') c+=32; low[i]=(char)c; }
    low[i] = 0;
    if (strstr(low,"chex")) return retail;		// Chex Quest (1/2/3): Ultimate-Doom format
    if (strstr(low,"doom2") || strstr(low,"plutonia") || strstr(low,"tnt")
	|| strstr(low,"freedoom2") || strstr(low,"freedm")) return commercial;
    if (strstr(low,"doomu") || strstr(low,"freedoom1")) return retail;
    if (strstr(low,"doom1")) return shareware;
    if (strstr(low,"doom"))  return registered;
    return commercial;
}

//
// IdentifyVersion
// Locate an IWAD and set the game mode.  Search order:
//   -iwad <file>  >  "iwad" in aidoom.cfg  >  iwads/  >  .  >  $DOOMWADDIR  >  Steam
//
void IdentifyVersion (void)
{
    char	path[1024];
    char	cfgval[512];
    int		mode = indetermined;
    char*	found = NULL;
    char*	doomwaddir;
    int		i, d, r, p;

    doomwaddir = getenv("DOOMWADDIR");

    // Single config file in the working directory (next to the binary).
    strcpy (basedefault, "aidoom.cfg");

    if (M_CheckParm ("-shdev"))
    {
	gamemode = shareware; devparm = true;
	D_AddFile (DEVDATA"doom1.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }
    if (M_CheckParm ("-regdev"))
    {
	gamemode = registered; devparm = true;
	D_AddFile (DEVDATA"doom.wad");
	D_AddFile (DEVMAPS"data_se/texture1.lmp");
	D_AddFile (DEVMAPS"data_se/texture2.lmp");
	D_AddFile (DEVMAPS"data_se/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }
    if (M_CheckParm ("-comdev"))
    {
	gamemode = commercial; devparm = true;
	D_AddFile (DEVDATA"doom2.wad");
	D_AddFile (DEVMAPS"cdata/texture1.lmp");
	D_AddFile (DEVMAPS"cdata/pnames.lmp");
	strcpy (basedefault,DEVDATA"default.cfg");
	return;
    }

    // 1) explicit -iwad <file>  (try as-given, then under ID0/)
    p = M_CheckParm ("-iwad");
    if (p && p < myargc-1)
    {
	char id0[1024];
	snprintf (id0, sizeof(id0), "ID0/%s", myargv[p+1]);
	if      (!access (myargv[p+1], R_OK)) found = IWAD_Strdup (myargv[p+1]);
	else if (!access (id0,         R_OK)) found = IWAD_Strdup (id0);
	if (found) mode = IWAD_ModeFromName (found);
    }

    // 2) "iwad <path>" from aidoom.cfg (written by the config app)
    if (!found && IWAD_CfgGet ("iwad", cfgval, sizeof(cfgval)) && cfgval[0])
    {
	char id0[1024];
	snprintf (id0, sizeof(id0), "ID0/%s", cfgval);
	if      (!access (cfgval, R_OK)) found = IWAD_Strdup (cfgval);
	else if (!access (id0,    R_OK)) found = IWAD_Strdup (id0);
	if (found) mode = IWAD_ModeFromName (found);
    }

    // 3) known names in:  iwads/  ->  .  ->  $DOOMWADDIR  (plus french doom2f.wad)
    if (!found)
    {
	const char* dirs[4]; int nd = 0;
	dirs[nd++] = "ID0";		// all game WADs live in run/ID0/ (refactor)
	dirs[nd++] = "iwads";
	dirs[nd++] = ".";
	if (doomwaddir && strcmp (doomwaddir, ".")) dirs[nd++] = doomwaddir;

	for (d=0; !found && d<nd; d++)
	{
	    snprintf (path, sizeof(path), "%s/doom2f.wad", dirs[d]);
	    if (!access (path, R_OK))
	    {
		found = IWAD_Strdup (path); mode = commercial;
		language = french; printf ("French version\n");
		break;
	    }
	    for (i=0; i < (int)(sizeof(known_iwads)/sizeof(known_iwads[0])); i++)
	    {
		snprintf (path, sizeof(path), "%s/%s", dirs[d], known_iwads[i].name);
		if (!access (path, R_OK))
		{ found = IWAD_Strdup (path); mode = known_iwads[i].mode; break; }
	    }
	}
    }

    // 4) Steam install locations
    if (!found)
    {
	// Default Steam library "common" folder, per OS.  We only probe the
	// default library (extra library folders on other drives live in
	// libraryfolders.vdf, which we don't parse) -- drop the IWAD in iwads/
	// if Steam installed it elsewhere.
	char roots[8][512]; int nr = 0;
	char* home = getenv ("HOME");
#if defined(__APPLE__)
	if (home)
	    snprintf (roots[nr++], 512, "%s/Library/Application Support/Steam/steamapps/common", home);
#elif defined(_WIN32)
	snprintf (roots[nr++], 512, "C:/Program Files (x86)/Steam/steamapps/common");
	snprintf (roots[nr++], 512, "C:/Program Files/Steam/steamapps/common");
#else	/* Linux / *BSD */
	if (home)
	{
	    snprintf (roots[nr++], 512, "%s/.steam/steam/steamapps/common", home);
	    snprintf (roots[nr++], 512, "%s/.local/share/Steam/steamapps/common", home);
	    snprintf (roots[nr++], 512, "%s/.steam/root/steamapps/common", home);
	    // Flatpak Steam (com.valvesoftware.Steam) sandboxed data dir.
	    snprintf (roots[nr++], 512, "%s/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common", home);
	}
#endif

	for (i=0; !found && i < (int)(sizeof(steam_iwads)/sizeof(steam_iwads[0])); i++)
	    for (r=0; r<nr; r++)
	    {
		snprintf (path, sizeof(path), "%s/%s", roots[r], steam_iwads[i].rel);
		if (!access (path, R_OK))
		{ found = IWAD_Strdup (path); mode = steam_iwads[i].mode; break; }
	    }
    }

    if (found)
    {
	printf ("IWAD: %s\n", found);
	gamemode = mode;
	D_AddFile (found);
	// DOOM1 + a doom2stuff.wad on hand -> auto-overlay it so the director can spawn
	// DOOM2 monsters and the super shotgun works (assets are absent from doom.wad).
	// (W_AddFile resolves the bare name under ID0/.)
	if (mode != commercial
	    && (!access ("ID0/doom2stuff.wad", R_OK) || !access ("doom2stuff.wad", R_OK)))
	{
	    D_AddFile ("doom2stuff.wad");
	    doom2_overlay = 1;
	    printf ("DOOM2 overlay: doom2stuff.wad -> DOOM2 monsters + super shotgun enabled\n");
	}
	return;
    }

    printf ("Game mode indeterminate -- no IWAD found "
	    "(looked in iwads/, ., $DOOMWADDIR, Steam).\n");
    gamemode = indetermined;
}

//
// Find a Response File
//
void FindResponseFile (void)
{
    int             i;
#define MAXARGVS        100
	
    for (i = 1;i < myargc;i++)
	if (myargv[i][0] == '@')
	{
	    FILE *          handle;
	    int             size;
	    int             k;
	    int             index;
	    int             indexinfile;
	    char    *infile;
	    char    *file;
	    char    *moreargs[20];
	    char    *firstargv;
			
	    // READ THE RESPONSE FILE INTO MEMORY
	    handle = fopen (&myargv[i][1],"rb");
	    if (!handle)
	    {
		printf ("\nNo such response file!");
		exit(1);
	    }
	    printf("Found response file %s!\n",&myargv[i][1]);
	    fseek (handle,0,SEEK_END);
	    size = ftell(handle);
	    fseek (handle,0,SEEK_SET);
	    file = malloc (size);
	    fread (file,size,1,handle);
	    fclose (handle);
			
	    // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
	    for (index = 0,k = i+1; k < myargc; k++)
		moreargs[index++] = myargv[k];
			
	    firstargv = myargv[0];
	    myargv = malloc(sizeof(char *)*MAXARGVS);
	    memset(myargv,0,sizeof(char *)*MAXARGVS);
	    myargv[0] = firstargv;
			
	    infile = file;
	    indexinfile = k = 0;
	    indexinfile++;  // SKIP PAST ARGV[0] (KEEP IT)
	    do
	    {
		myargv[indexinfile++] = infile+k;
		while(k < size &&
		      ((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
		    k++;
		*(infile+k) = 0;
		while(k < size &&
		      ((*(infile+k)<= ' ') || (*(infile+k)>'z')))
		    k++;
	    } while(k < size);
			
	    for (k = 0;k < index;k++)
		myargv[indexinfile++] = moreargs[k];
	    myargc = indexinfile;
	
	    // DISPLAY ARGS
	    printf("%d command-line args:\n",myargc);
	    for (k=1;k<myargc;k++)
		printf("%s\n",myargv[k]);

	    break;
	}
}


//
// D_DoomMain
//
//
// D_PrintHelp
// Print every command-line flag aidoom understands, grouped, then the caller
// exits.  Triggered by -help / -h / -? / /?.  Keep in sync with AIDOOM_PARAMETERS.md.
//
static void D_PrintHelp (void)
{
    puts (
"aidoom -- SDL3 DOOM with an AI co-op buddy + LLM monster director.\n"
"Usage: aidoom [options]   (bring your own IWAD)\n"
"\n"
"GAME / LEVEL\n"
"  -iwad <file>      IWAD to use (doom/doom2/plutonia/tnt/freedoom*); else auto-detect\n"
"  -file <wad>...    load extra PWAD(s) over the IWAD (repeatable)\n"
"  -warp <e> <m>     jump to episode/map (commercial: -warp <map>); default 1 1\n"
"  -episode <n>      start episode (registered/retail)\n"
"  -skill <1-5>      1 ITYTD .. 4 UV .. 5 Nightmare (default 3)\n"
"  -nomonsters       spawn no monsters\n"
"  -respawn          monsters respawn after death\n"
"  -fast             fast monsters\n"
"  -turbo <%>        player speed percent (default 100)\n"
"  -loadgame <slot>  load a saved game on startup\n"
"\n"
"VIDEO\n"
"  -1 / -2 / -3 / -4 resolution scale 1..4 (320x200 .. 1280x800)\n"
"  -render <1-7>     resolution scale (overrides -1..-4)\n"
"  -fullscreen       force fullscreen        -window      force windowed\n"
"  -nomouse          disable mouse input     -nograb      don't grab the mouse\n"
"  -nodraw / -noblit headless/benchmark (skip rendering / skip blit)\n"
"\n"
"AI DIRECTOR / CO-OP BUDDY\n"
"  -coop             rule-based co-op buddy (player 2; map needs Player_2_Start)\n"
"  -aicoop           AI buddy: rule-based base + LLM director (opens TCP 31666)\n"
"  -buddyreact <t>   buddy first-shot delay in tics (0=instant, ~14 ~= human)\n"
"  -aidirector [port] LLM monster director; opens TCP listener (default 31666)\n"
"  -aidemo           built-in test director (no Ollama)\n"
"  -director         rule-based L4D-style spawn director (offline, no LLM)\n"
"  -infight          monsters' projectiles hurt same-species (infighting on)\n"
"  -nofriendlyfire   player and AI buddy can't damage each other (alias -noff)\n"
"\n"
"DEMOS\n"
"  -record <lmp>     record a demo      -playdemo <lmp>  play a demo\n"
"  -timedemo <lmp>   benchmark a demo   -maxdemo <n>     max demo size\n"
"\n"
"NETWORK (LAN)\n"
"  -net / -server    host a game        -connect/-netclient <ip>  join a host\n"
"  -port <n>         UDP port (default 5029)   -netplayers <n>  max players\n"
"  -deathmatch / -altdeath   deathmatch modes   -timer <min>  frag time limit\n"
"\n"
"DEV / MISC\n"
"  -devparm          developer mode (cheats, fps)   -debugfile  write debug.txt\n"
"  -cdrom            CD-ROM save paths\n"
"  -help / -h / -?   show this help and exit\n"
"\n"
"See AIDOOM_PARAMETERS.md for the full reference, and run/README.md for the\n"
"launchers (start_aidoom.sh / start_aibuddy.sh) and the GUI launcher."
    );
}

void D_DoomMain (void)
{
    int             p;
    char                    file[256];

    FindResponseFile ();

    // -help / -h / -? / /?: print the flag reference and exit.
    if (M_CheckParm ("-help") || M_CheckParm ("-h")
	|| M_CheckParm ("-?") || M_CheckParm ("/?"))
    {
	D_PrintHelp ();
	exit (0);
    }

    // Chocolate/Crispy multiplayer interop (clean-room reimpl; see i_udp.c/d_netcl.c).
    // -querychoc <host[:port]>           query a server and exit
    p = M_CheckParm ("-querychoc");
    if (p && p < myargc-1) { I_QueryChocServer (myargv[p+1]); exit (0); }

    // -chocsyn <host[:port]> [version]   SYN handshake test and exit
    p = M_CheckParm ("-chocsyn");
    if (p && p < myargc-1)
    {
	const char* ver = (p < myargc-2 && myargv[p+2][0] != '-') ? myargv[p+2] : "Chocolate Doom 3.1.1";
	I_ConnectChocServer (myargv[p+1], ver, 2 /*commercial*/, 1 /*doom2*/);
	exit (0);
    }

    // -netclient <host[:port]> [version] full connect/launch/gamestart self-test, exit
    p = M_CheckParm ("-netclient");
    if (p && p < myargc-1)
    {
	const char* ver = (p < myargc-2 && myargv[p+2][0] != '-') ? myargv[p+2] : "Chocolate Doom 3.1.1";
	I_NetClientTest (myargv[p+1], ver, 2 /*commercial*/, 1 /*doom2*/);
	exit (0);
    }

    IdentifyVersion ();
	
    setbuf (stdout, NULL);
    modifiedgame = false;
	
    nomonsters = M_CheckParm ("-nomonsters");
    respawnparm = M_CheckParm ("-respawn");
    fastparm = M_CheckParm ("-fast");
    // -infight: monster same-species infighting (was -friendlyfire).
    { extern int infight; infight = M_CheckParm ("-infight") ? 1 : 0; }
    // -nofriendlyfire (alias -noff): the player and the AI buddy can't damage each other.
    { extern int ff_protect;
      ff_protect = (M_CheckParm ("-nofriendlyfire") || M_CheckParm ("-noff")) ? 1 : 0; }
    devparm = M_CheckParm ("-devparm");
    if (M_CheckParm ("-altdeath"))
	deathmatch = 2;
    else if (M_CheckParm ("-deathmatch"))
	deathmatch = 1;

    switch ( gamemode )
    {
      case retail:
	sprintf (title,
		 "                         "
		 "The Ultimate DOOM Startup v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
      case shareware:
	sprintf (title,
		 "                            "
		 "DOOM Shareware Startup v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
      case registered:
	sprintf (title,
		 "                            "
		 "DOOM Registered Startup v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
      case commercial:
	sprintf (title,
		 "                         "
		 "DOOM 2: Hell on Earth v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
/*FIXME
       case pack_plut:
	sprintf (title,
		 "                   "
		 "DOOM 2: Plutonia Experiment v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
      case pack_tnt:
	sprintf (title,
		 "                     "
		 "DOOM 2: TNT - Evilution v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
*/
      default:
	sprintf (title,
		 "                     "
		 "Public DOOM - v%i.%i"
		 "                           ",
		 VERSION_NUM/100,VERSION_NUM%100);
	break;
    }
    
    printf ("%s\n",title);

    if (devparm)
	printf(D_DEVSTR);
    
    // turbo option
    if ( (p=M_CheckParm ("-turbo")) )
    {
	int     scale = 200;
	extern int forwardmove[2];
	extern int sidemove[2];
	
	if (p<myargc-1)
	    scale = atoi (myargv[p+1]);
	if (scale < 10)
	    scale = 10;
	if (scale > 400)
	    scale = 400;
	printf ("turbo scale: %i%%\n",scale);
	forwardmove[0] = forwardmove[0]*scale/100;
	forwardmove[1] = forwardmove[1]*scale/100;
	sidemove[0] = sidemove[0]*scale/100;
	sidemove[1] = sidemove[1]*scale/100;
    }
    
    // add any files specified on the command line with -file wadfile
    // to the wad list
    //
    // convenience hack to allow -wart e m to add a wad file
    // prepend a tilde to the filename so wadfile will be reloadable
    p = M_CheckParm ("-wart");
    if (p)
    {
	myargv[p][4] = 'p';     // big hack, change to -warp

	// Map name handling.
	switch (gamemode )
	{
	  case shareware:
	  case retail:
	  case registered:
	    sprintf (file,"~"DEVMAPS"E%cM%c.wad",
		     myargv[p+1][0], myargv[p+2][0]);
	    printf("Warping to Episode %s, Map %s.\n",
		   myargv[p+1],myargv[p+2]);
	    break;
	    
	  case commercial:
	  default:
	    p = atoi (myargv[p+1]);
	    if (p<10)
	      sprintf (file,"~"DEVMAPS"cdata/map0%i.wad", p);
	    else
	      sprintf (file,"~"DEVMAPS"cdata/map%i.wad", p);
	    break;
	}
	D_AddFile (file);
    }
	
    p = M_CheckParm ("-file");
    if (p)
    {
	// the parms after p are wadfile/lump names,
	// until end of parms or another - preceded parm
	modifiedgame = true;            // homebrew levels
	while (++p != myargc && myargv[p][0] != '-')
	    D_AddFile (myargv[p]);
    }

    p = M_CheckParm ("-playdemo");

    if (!p)
	p = M_CheckParm ("-timedemo");

    if (p && p < myargc-1)
    {
	sprintf (file,"%s.lmp", myargv[p+1]);
	D_AddFile (file);
	printf("Playing demo %s.lmp.\n",myargv[p+1]);
    }
    
    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

		
    p = M_CheckParm ("-skill");
    if (p && p < myargc-1)
    {
	startskill = myargv[p+1][0]-'1';
	autostart = true;
    }

    p = M_CheckParm ("-episode");
    if (p && p < myargc-1)
    {
	startepisode = myargv[p+1][0]-'0';
	startmap = 1;
	autostart = true;
    }
	
    p = M_CheckParm ("-timer");
    if (p && p < myargc-1 && deathmatch)
    {
	int     time;
	time = atoi(myargv[p+1]);
	printf("Levels will end after %d minute",time);
	if (time>1)
	    printf("s");
	printf(".\n");
    }

    p = M_CheckParm ("-avg");
    if (p && p < myargc-1 && deathmatch)
	printf("Austin Virtual Gaming: Levels will end after 20 minutes\n");

    p = M_CheckParm ("-warp");
    if (p && p < myargc-1)
    {
	if (gamemode == commercial)
	    startmap = atoi (myargv[p+1]);
	else
	{
	    startepisode = myargv[p+1][0]-'0';
	    // "-warp E" (no map) is allowed -> default to map 1.  Reading
	    // myargv[p+2] unconditionally walked off the end of argv (crash).
	    startmap = (p < myargc-2 && myargv[p+2][0] != '-') ? myargv[p+2][0]-'0' : 1;
	}
	autostart = true;
    }
    
    // init subsystems
    printf ("V_Init: allocate screens.\n");
    V_Init ();

    printf ("M_LoadDefaults: Load system defaults.\n");
    M_LoadDefaults ();              // load before initing other systems

    printf ("Z_Init: Init zone memory allocation daemon. \n");
    Z_Init ();

    printf ("W_Init: Init WADfiles.\n");
    W_InitMultipleFiles (wadfiles);
printf("added\n");
    

    // Check for -file in shareware
    if (modifiedgame)
    {
	// These are the lumps that will be checked in IWAD,
	// if any one is not present, execution will be aborted.
	char name[23][8]=
	{
	    "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
	    "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
	    "dphoof","bfgga0","heada1","cybra1","spida1d1"
	};
	int i;
	
	if ( gamemode == shareware)
	    I_Error("\nYou cannot -file with the shareware "
		    "version. Register!");

	// Check for fake IWAD with right name,
	// but w/o all the lumps of the registered version. 
	if (gamemode == registered)
	    for (i = 0;i < 23; i++)
		if (W_CheckNumForName(name[i])<0)
		    I_Error("\nThis is not the registered version.");
    }
    
    // Iff additonal PWAD files are used, print modified banner
    if (modifiedgame)
    {
	/*m*/printf (
	    "===========================================================================\n"
	    "ATTENTION:  This version of DOOM has been modified.  If you would like to\n"
	    "get a copy of the original game, call 1-800-IDGAMES or see the readme file.\n"
	    "        You will not receive technical support for modified games.\n"
	    "                      press enter to continue\n"
	    "===========================================================================\n"
	    );
	getchar ();
    }
	

    // Check and print which version is executed.
    switch ( gamemode )
    {
      case shareware:
      case indetermined:
	printf (
	    "===========================================================================\n"
	    "                                Shareware!\n"
	    "===========================================================================\n"
	);
	break;
      case registered:
      case retail:
      case commercial:
	printf (
	    "===========================================================================\n"
	    "                 Commercial product - do not distribute!\n"
	    "         Please report software piracy to the SPA: 1-800-388-PIR8\n"
	    "===========================================================================\n"
	);
	break;
	
      default:
	// Ouch.
	break;
    }

    printf ("M_Init: Init miscellaneous info.\n");
    M_Init ();

    printf ("R_Init: Init DOOM refresh daemon - ");
    R_Init ();

    printf ("\nP_Init: Init Playloop state.\n");
    P_Init ();

    Heretic_Init ();		// fill the appended Heretic monster states/mobjinfo
    Hexen_Init ();		// fill the appended Hexen monster states/mobjinfo
    Freedoom_Init ();		// clone the DOOM2 monsters into the MT_FD_* slots
    RevMarine_Init ();		// (G) fill the revived-friendly-marine states/mobjinfo
    Invent_Init ();		// (J) fill the artifact-inventory pickup states/mobjinfo

    printf ("I_Init: Setting up machine state.\n");
    I_Init ();

    // -connect <host[:port]> [version] -- join a Chocolate/Crispy server as a
    // client; flags D_CheckNetGame onto the choc path (d_net.c / d_netcl.c).
    p = M_CheckParm ("-connect");
    if (p && p < myargc-1)
    {
	extern boolean	choc_client;
	extern char	choc_host[];
	extern char	choc_version[];
	choc_client = true;
	strncpy (choc_host, myargv[p+1], 255);  choc_host[255] = 0;
	if (p < myargc-2 && myargv[p+2][0] != '-')
	{ strncpy (choc_version, myargv[p+2], 127);  choc_version[127] = 0; }
    }

    printf ("D_CheckNetGame: Checking network game status.\n");
    D_CheckNetGame ();

    // -coop or -aicoop: enable the co-op companion (player 2).  -coop is the
    // autonomous rule-based bot; -aicoop adds the LLM director layer (the
    // director sets the buddy's tactics over the same TCP transport as the
    // monsters -- see p_ai_coop.c / p_ai_llm.c).  The two flags are mutually
    // exclusive -- specifying both aborts in P_AICoop_Init.  Must run after
    // D_CheckNetGame (which sets playeringame[]) and before the first level.
    P_AICoop_Init ();
    P_Director_Init ();		// L4D-style rule-based spawn director (-director)
    G_AgentInit ();		// full agent/LLM control of the player (-aiplayer)

    printf ("S_Init: Setting up sound.\n");
    S_Init (snd_SfxVolume /* *8 */, snd_MusicVolume /* *8*/ );

    printf ("HU_Init: Setting up heads up display.\n");
    HU_Init ();

    C_Init ();		// developer console (toggle with `)

    printf ("HU_Buddy_Init: Companion HUD.\n");
    HU_Buddy_Init ();	// small top-strip HUD for the co-op buddy

    printf ("ST_Init: Init status bar.\n");
    ST_Init ();

    // check for a driver that wants intermission stats
    p = M_CheckParm ("-statcopy");
    if (p && p<myargc-1)
    {
	// for statistics driver
	extern  void*	statcopy;                            

	statcopy = (void*)atoi(myargv[p+1]);
	printf ("External statistics registered.\n");
    }
    
    // start the apropriate game based on parms
    p = M_CheckParm ("-record");

    if (p && p < myargc-1)
    {
	G_RecordDemo (myargv[p+1]);
	autostart = true;
    }
	
    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
	singledemo = true;              // quit after one demo
	G_DeferedPlayDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
	G_TimeDemo (myargv[p+1]);
	D_DoomLoop ();  // never returns
    }
	
    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
	sprintf(file, SAVEGAMENAME"%c.dsg",myargv[p+1][0]);	// always ID0/ -- no c:\doomdata
	G_LoadGame (file);
    }
	

    if ( gameaction != ga_loadgame )
    {
	if (autostart || netgame)
	    G_InitNew (startskill, startepisode, startmap);
	else
	    D_StartTitle ();                // start up intro loop

    }

    D_DoomLoop ();  // never returns
}
