# Makefile.msvc -- native Windows build of aiDoom with Visual Studio 2019 (NMake).
#
# Usage (from a "x86 Native Tools Command Prompt for VS 2019", in files\):
#     nmake /f Makefile.msvc
# or override the SDL location:
#     nmake /f Makefile.msvc SDL=C:\path\to\SDL-1.2.15
#
# Produces aidoom.exe (Win32/x86, SDL3) and copies SDL3.dll next to it.

SDL = C:\Source\SDL3

CC = cl
CFLAGS = /nologo /O2 /MD /W3 /I"$(SDL)\include" \
	/DSDL_MAIN_HANDLED \
	/D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE \
	/D_WINSOCK_DEPRECATED_NO_WARNINGS /DWIN32 /D_WINDOWS

LIBS = "$(SDL)\lib\x86\SDL3.lib" ws2_32.lib
LDFLAGS = /link /SUBSYSTEM:CONSOLE

RES = aidoom.res

OBJS = \
	am_map.obj c_console.obj d_items.obj d_main.obj d_net.obj d_netcl.obj doomdef.obj doomstat.obj \
	dstrings.obj f_finale.obj f_wipe.obj g_game.obj hu_buddy.obj hu_lib.obj hu_stuff.obj \
	i_main.obj i_mus.obj i_net.obj i_udp.obj i_sound.obj i_system.obj i_video.obj i_voice.obj info.obj \
	m_argv.obj m_bbox.obj m_cheat.obj m_fixed.obj m_menu.obj m_misc.obj \
	m_random.obj m_swap.obj p_ai_director.obj p_ai_llm.obj p_ai_coop.obj p_ceilng.obj p_doors.obj p_enemy.obj \
	p_floor.obj p_inter.obj p_lights.obj p_map.obj p_maputl.obj p_mobj.obj \
	p_plats.obj p_pspr.obj p_saveg.obj p_setup.obj p_sight.obj p_spec.obj \
	p_switch.obj p_telept.obj p_tick.obj p_user.obj r_bsp.obj r_data.obj \
	r_draw.obj r_main.obj r_plane.obj r_segs.obj r_sky.obj r_things.obj \
	s_sound.obj sounds.obj stb_vorbis.obj st_lib.obj st_stuff.obj tables.obj v_png.obj v_video.obj \
	w_wad.obj wi_stuff.obj z_zone.obj

all: aidoom.exe

aidoom.exe: $(OBJS) $(RES)
	$(CC) $(CFLAGS) /Fe:aidoom.exe $(OBJS) $(RES) $(LDFLAGS) $(LIBS)
	@if exist "$(SDL)\lib\x86\SDL3.dll" copy /Y "$(SDL)\lib\x86\SDL3.dll" SDL3.dll >nul

$(RES): aidoom.rc ..\aidoom.ico
	rc /nologo /fo $(RES) aidoom.rc

.c.obj:
	$(CC) $(CFLAGS) /c $<

clean:
	-del *.obj *.res aidoom.exe SDL.dll SDL3.dll 2>nul
