# Makefile.msvc -- native Windows build of aiDoom with Visual Studio 2019 (NMake).
#
# Usage (from a "x86 Native Tools Command Prompt for VS 2019", in files\):
#     nmake /f Makefile.msvc
# or override the SDL location:
#     nmake /f Makefile.msvc SDL=C:\path\to\SDL-1.2.15
#
# Produces aidoom.exe (Win32/x86, SDL3) and copies SDL3.dll next to it.

SDL = C:\Source\SDL3

CC = cl
# /Zi + /DEBUG (below): emit aidoom.pdb.  Codegen is unchanged from plain /O2, but a
# shipped PDB lets the crash handler's minidump (i_main.c) symbolise to exact
# functions/lines instead of guessing against a mismatched build.
CFLAGS = /nologo /O2 /Zi /MD /W3 /I"$(SDL)\include" \
	/DSDL_MAIN_HANDLED \
	/D_CRT_SECURE_NO_WARNINGS /D_CRT_NONSTDC_NO_DEPRECATE \
	/D_WINSOCK_DEPRECATED_NO_WARNINGS /DWIN32 /D_WINDOWS

LIBS = "$(SDL)\lib\x86\SDL3.lib" ws2_32.lib dbghelp.lib
LDFLAGS = /link /SUBSYSTEM:CONSOLE /DEBUG

RES = aidoom.res

OBJS = \
	am_map.obj c_console.obj c_llm.obj d_deh.obj d_items.obj d_main.obj d_net.obj d_netcl.obj doomdef.obj doomstat.obj \
	dsdhacked.obj dstrings.obj f_finale.obj f_wipe.obj g_agent.obj g_game.obj hu_buddy.obj hu_lib.obj hu_stuff.obj \
	i_compat.obj i_main.obj i_mus.obj i_opl.obj opl3.obj i_net.obj i_udp.obj i_sound.obj i_system.obj i_video.obj i_voice.obj id24.obj info.obj \
	heretic.obj freedoom.obj hexen.obj \
	m_argv.obj m_bbox.obj m_cheat.obj m_fixed.obj m_menu.obj m_misc.obj \
	m_random.obj m_swap.obj p_ai_director.obj p_ai_llm.obj p_ai_coop.obj p_ceilng.obj p_doors.obj p_enemy.obj \
	p_floor.obj p_inter.obj p_invent.obj p_inv_heretic.obj p_lights.obj p_map.obj p_maputl.obj p_mobj.obj p_morph.obj \
	p_boomsp.obj p_genlin.obj p_mbf.obj p_plats.obj p_pspr.obj p_saveg.obj p_secdrone.obj p_setup.obj p_sight.obj p_spec.obj \
	p_switch.obj p_telept.obj p_tick.obj p_turret.obj p_user.obj revmarine.obj r_bsp.obj r_data.obj \
	r_draw.obj r_main.obj r_plane.obj r_segs.obj r_skydefs.obj r_sky.obj r_things.obj \
	s_sound.obj sounds.obj stb_vorbis.obj st_lib.obj st_stuff.obj tables.obj u_mapinfo.obj v_png.obj v_video.obj \
	w_wad.obj wi_stuff.obj w_json.obj z_zone.obj miniz.obj

all: aidoom.exe

aidoom.exe: $(OBJS) $(RES)
	$(CC) $(CFLAGS) /Fe:aidoom.exe $(OBJS) $(RES) $(LDFLAGS) $(LIBS)
	@if exist "$(SDL)\lib\x86\SDL3.dll" copy /Y "$(SDL)\lib\x86\SDL3.dll" SDL3.dll >nul

$(RES): aidoom.rc ..\aidoom.ico
	rc /nologo /fo $(RES) aidoom.rc

.c.obj:
	$(CC) $(CFLAGS) /c $<

clean:
	-del *.obj *.res aidoom.exe SDL.dll SDL3.dll 2>nul
