#!/usr/bin/env python3
# Bake DejaVuSansMono ASCII 32..126 into tools/font_atlas.h (8-bit alpha atlas).
from PIL import Image, ImageDraw, ImageFont
FONT="/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"; SIZE=16
first,count=32,95
font=ImageFont.truetype(FONT,SIZE)
asc,desc=font.getmetrics(); ch=asc+desc
cw=int(round(font.getlength("M")))
aw=cw*count
img=Image.new("L",(aw,ch),0); d=ImageDraw.Draw(img)
for i in range(count):
    d.text((i*cw,0), chr(first+i), fill=255, font=font)
data=img.tobytes()
assert len(data)==aw*ch
with open("tools/font_atlas.h","w") as f:
    f.write("// Generated by tools/bake_font.py (DejaVuSansMono %dpx ASCII %d..%d)\n"%(SIZE,first,first+count-1))
    f.write("#ifndef FONT_ATLAS_H\n#define FONT_ATLAS_H\n")
    f.write("#define FONT_CW %d\n#define FONT_CH %d\n#define FONT_FIRST %d\n#define FONT_COUNT %d\n#define FONT_AW %d\n"%(cw,ch,first,count,aw))
    f.write("static const unsigned char font_alpha[%d] = {\n"%len(data))
    for i in range(0,len(data),24):
        f.write(" "+",".join(str(b) for b in data[i:i+24])+",\n")
    f.write("};\n#endif\n")
print("font_atlas.h: cell %dx%d, atlas %dx%d, %d bytes"%(cw,ch,aw,ch,len(data)))
